# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  my_job:
    runs-on: ubuntu-latest

    steps:
      - run: echo "My action jobs"
  
  secret_printer:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "My secret is: ${{ secrets.SECRET_VALUE}}"

  env_example:
    runs-on: ubuntu-latest
    environment:
      name: test_env
      url: "https://github.com"
    
    steps:
      - name: "Print secret from env"
        run: |
          echo "ENV secret ${{ secrets.ENV_SECRET1 }}"

  output_example_steps:
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.var_source_step.outputs.var1_name }}
      build_time: ${{ steps.var_source_step.outputs.var2_date }}

    steps:
      - name: Create-Variables
        id: var_source_step
        run: |
          echo "var1_name=TechSkool" >> $GITHUB_OUTPUT
          echo "var2_date=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

      - name: Access-Variables
        run: |
            echo "Value: ${{ steps.var_source_step.outputs.var1_name }}"
            echo "Value ${{ steps.var_source_step.outputs.var2_date }}"
        

  output_example_jobs:
    needs: output_example_steps
    runs-on: ubuntu-latest

    steps:
      - name: "Reading other jobs value"
        run: |
            echo "Other jobs value: ${{ needs.output_example_steps.outputs.app_name }}"
            echo "Other jobs value ${{ needs.output_example_steps.outputs.build_time }}"